redis

diff --git a/build b/build
--- a/build
+++ b/build
@@ -121,6 +121,31 @@ if [ "$(type -p npm)" == "" ]; then
 fi
 echo "STATUS	: npm installed"
 
+if [ "$(type -p redis-cli)" == "" ]; then
+	echo "COMMAND	: sudo apt-get install -y build-essential"
+	sudo apt-get install -y build-essential
+	if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
+	if [ ! -e redis-2.8.19 ]; then 
+		echo "COMMAND	: wget http://download.redis.io/releases/redis-2.8.19.tar.gz"
+		wget http://download.redis.io/releases/redis-2.8.19.tar.gz
+		if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
+		tar -xzf redis-2.8.19.tar.gz
+	fi
+	pushd redis-2.8.19
+	make 
+	sudo make install
+	popd
+fi
+echo "INSTALL	: redis installed"
+
+npm list kue
+if [ $? -ne 0 ]; then
+  echo "INSTALL	: sudo npm install kue"
+  npm install kue
+  if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
+fi
+echo "INSTALL	: kue installed"
+
 if [ "$(type -p grunt)" == "" ]; then
   echo "INSTALL	: sudo npm install -g grunt-cli"
   sudo npm install -g grunt-cli
@@ -140,7 +165,8 @@ if [ ! -e node_modules ]; then
 fi
 echo "STATUS	: local node_modules installed"
 
-if [ "$(type -p express)" == "" ]; then
+npm list express
+if [ $? -ne 0 ]; then
   echo "INSTALL	: express " 
   npm install express
   if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
diff --git a/fire/web b/fire/web
--- a/fire/web
+++ b/fire/web
@@ -38,6 +38,15 @@ if [ "$1" == "-k" ] || [ "$1" == "-r" ]; then
 fi
 
 if [ "$1" == "-s" ] || [ "$1" == "-r" ]; then
+  echo "ACTION	: Checking for redis"
+  ps -ef | grep -v grep | grep redis-server 
+  if [ $? == 0 ]; then
+	  echo "STATUS	: redis-server is available"
+  else
+	  echo "STATUS	: starting redis-server"
+	  redis-server&
+	  if [ $? != 0 ]; then echo "ERROR	: could not launch redis-server"; exit; fi
+  fi
   echo "ACTION	: Start FireREST web server in background ($1)"
   ps -eo pid,args | grep node.*[f]irerest\.js > /dev/null
   if [ $? == 0 ]; then
