grunt

diff --git a/build b/build
--- a/build
+++ b/build
@@ -51,8 +51,11 @@ if [ "$(type -p grunt)" == "" ]; then
   echo "INSTALL	: sudo npm install -g grunt-cli"
   sudo npm install -g grunt-cli
   if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
-  echo "INSTALL	: sudo npm install -g grunt@0.4.5"
+  echo "INSTALL	: npm install -g grunt@0.4.5"
   npm install grunt@0.4.5 --save-dev
+  if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
+  echo "INSTALL	: npm install -g grunt-contrib-uglify"
+  npm install -g grunt-contrib-uglify
   if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
 fi
 
