...

diff --git a/build b/build
--- a/build
+++ b/build
@@ -44,11 +44,21 @@ function build_git() {
 
 if [ "$FIREREST_CONFIG" == "" ]; then FIREREST_CONFIG=examples/cfg-firepick-delta.json; fi
 
+if [ "$(type -p bc)" == "" ]; then
+  echo "INSTALL : bc"
+  sudo apt-key update;
+  sudo apt-get update;
+  sudo apt-get install bc;
+  if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
+fi
+echo "STATUS	: bc installed"
+
 if [ "$(type -p tmux)" == "" ]; then
   echo "INSTALL	: tmux"
   sudo apt-get install tmux
   if [ $? -ne 0 ]; then echo "ERROR	: installation failed"; exit -1; fi
 fi
+echo "STATUS	: tmux installed"
 
 if [ "$(type -p lsb_release)" == "" ]; then
   echo "INSTALL	: lsb_release"
diff --git a/fire/calibrate b/fire/calibrate
--- a/fire/calibrate
+++ b/fire/calibrate
@@ -44,7 +44,11 @@ function calcoffset() {
 
 function calcoffsetAt() {
   imageAt $1
-  firesight -ji 0 -p FireSight/json/calcOffset.json -Dtemplate=$IMAGES/$2.jpg -i $IMAGES/$1.jpg 
+  RESULT=`firesight -ji 0 -p FireSight/json/calcOffset.json -Dtemplate=$IMAGES/$2.jpg -i $IMAGES/$1.jpg`	
+  RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit -1; fi
+  DX=`echo $RESULT | grep -o -E "dx.:[-0-9.+]+" | grep -o -E "[-0-9.+]+"`
+  DY=`echo $RESULT | grep -o -E "dy.:[-0-9.+]+" | grep -o -E "[-0-9.+]+"`
+  echo "STATUS	: dx=$DX dy=$DY"
 }
 
 if [ "$1" == "-o" ]; then
