camera

diff --git a/fire/upgrade b/fire/upgrade
--- a/fire/upgrade
+++ b/fire/upgrade
@@ -14,11 +14,37 @@ if [ $? -ne 0 ]; then
   exit -1;
 fi
 
+if [ "$(type -p jshint)" == "" ]; then
+	echo "COMMAND	: sudo npm install -g jshint"
+	sudo npm install -g jshint
+	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+fi
+echo "STATUS	: jshint installed"
+
+NODE_VERSION=`node --version`
+echo "NODE	: $NODE_VERSION"
+if [[ $NODE_VERSION < v0.12.* ]]; then
+	echo "STATUS	: upgrading node"
+	echo "COMMAND	: sudo npm cache clean -f"
+	sudo npm cache clean -f
+	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+	echo "COMMAND	: sudo npm install -g n"
+	sudo npm install -g n
+	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+	echo "COMMAND	: sudo n stable"
+	sudo n stable
+	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+fi
+
+echo "COMMAND	: npm install"
+npm install
+RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+
 echo "SUDO	: verifying sudo privilege for changing machine configuration"
 sudo -K
 sudo echo "SUDO	: confirmed"
 if [ "$1" == "-a" ]; then
-  echo "STATUS	: full buid requested (-a)"
+  echo "STATUS	: full build requested (-a)"
   rm version-*
 fi
 echo "LOG	: `pwd`/build.log (started)"
