node0.12

diff --git a/fire/upgrade b/fire/upgrade
--- a/fire/upgrade
+++ b/fire/upgrade
@@ -7,6 +7,14 @@ echo "HELP	: fire/upgrade -a   # rebuild everything"
 
 fire/web -k
 
+if [ "$(arch)" != "armv6l" ] || [ "$(lsb_release -is)" != "Debian" ] ;then
+  RASPBIAN=0
+  echo "SYSTEM	: other (FireFUSE not supported)"
+else
+  RASPBIAN=1
+  echo "SYSTEM	: Raspberry Pi with Rasbian"
+fi
+
 echo "GIT	: `git config remote.origin.url`"
 git pull
 if [ $? -ne 0 ]; then
@@ -24,16 +32,33 @@ echo "STATUS	: jshint installed"
 NODE_VERSION=`node --version`
 echo "NODE	: $NODE_VERSION"
 if [[ $NODE_VERSION < v0.12.* ]]; then
-	echo "STATUS	: upgrading node"
-	echo "COMMAND	: sudo npm cache clean -f"
-	sudo npm cache clean -f
-	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
-	echo "COMMAND	: sudo npm install -g n"
-	sudo npm install -g n
-	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
-	echo "COMMAND	: sudo n stable"
-	sudo n stable
-	RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+	if [ $RASPBIAN -eq 1 ]; then
+		pushd ..
+		echo "NODE	: installing node-v0.12.0-linux-arm-pi.tar.gz"
+		wget https://s3-eu-west-1.amazonaws.com/conoroneill.net/wp-content/uploads/2015/02/node-v0.12.0-linux-arm-pi.tar.gz
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		echo "NODE	: tar -zxvf node-v0.12.0-linux-arm-pi.tar.gz"
+		tar -zxvf node-v0.12.0-linux-arm-pi.tar.gz
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		echo "NODE	: cd node-v0.12.0-linux-arm-pi"
+		cd node-v0.12.0-linux-arm-pi
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		echo "NODE	: sudo cp -R * /usr/local/"
+		sudo cp -R * /usr/local/
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		popd
+	else
+		echo "STATUS	: upgrading node"
+		echo "COMMAND	: sudo npm cache clean -f"
+		sudo npm cache clean -f
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		echo "COMMAND	: sudo npm install -g n"
+		sudo npm install -g n
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+		echo "COMMAND	: sudo n stable"
+		sudo n stable
+		RC=$?; if [ $RC -ne 0 ]; then echo "ERROR	: $RC"; exit $RC; fi
+	fi
 fi
 
 echo "COMMAND	: npm install"
